<a href="https://colab.research.google.com/github/CVasquezroque/SCI-IA2024/blob/main/SIC_Sesion_11_Indexing_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://raw.githubusercontent.com/CVasquezroque/SCI-IA2024/main/assets/CTC-logo.png" width="250">

\\

# Introducción a la Indexación y Slicing en NumPy

En este laboratorio, profundizaremos en las técnicas de indexación y slicing de arrays en NumPy. NumPy es una biblioteca fundamental para la computación científica en Python, y manejar arrays de manera eficiente es crucial para muchas aplicaciones en ciencia de datos y aprendizaje automático. Aprenderemos cómo acceder a elementos individuales, secciones específicas de arrays y cómo manipular arrays de manera avanzada utilizando indexación y slicing.

En este notebook podrás:
- Realizar indexación básica en arrays unidimensionales.
- Explorar la indexación multidimensional.
- Aplicar slicing en arrays unidimensionales.
- Entender y utilizar slicing en arrays multidimensionales.
- Implementar técnicas avanzadas como Fancy Indexing.

## Tabla de Contenidos

1. [Indexación Básica en Arrays Unidimensionales](SIC_Sesion_11_Indexing_Slicing.ipynb#1-indexación-básica-en-arrays-unidimensionales)



\\

<img src="https://raw.githubusercontent.com/CVasquezroque/SCI-IA2024/main/assets/CTC-icon.png" width="25" height="25">


## 1.-Indexación-Básica-en-Arrays

Si estas familiarizado con la indexación de listas estándar de Python, la indexación en NumPy te resultará bastante familiar. En un array unidimensional, el valor  i-ésimo  (contando desde cero) se puede acceder especificando el índice deseado entre corchetes, al igual que con las listas de Python:


In [ ]:
import numpy as np

a=np.array([0,1,2,3])



Accedemos al primer elemento de un array de la siguiente manera:

In [ ]:
a[0]

0

En un array multidimensional, los elementos se pueden acceder de diferentes maneras.

El método va a variar dependiendo si quieres acceder a un elemento específico o a una sección de elementos.

Por ejemplo, observemos el siguiente caso:

In [ ]:
b=np.array([[0,1,2,3],
            [4,5,6,7],
            [8,9,10,11]])

Cuando usamos el índice cero, no obtenemos el primer elemento de la matriz, sino la primera fila de la matriz.

In [ ]:
b[0]

array([0, 1, 2, 3])

Si queremos acceder al primer elemento de la matriz, debemos usar dos índices, uno para la fila y otro para la columna.

In [ ]:
b[0][1]

1

In [ ]:
b[0,1]

1

En el primer caso, al usar dos índices, primero obtenemos la fila con b[0] y luego al indicar [1] estamos accediendo al segundo elemento de la fila.

En el segundo caso, al usar [0,1], estamos indicando que queremos acceder al elemento de la fila 0 y columna 1, siendo el mismo resultado que en el caso anterior.

Otro ejemplo:

In [ ]:
a2=np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a2[0,2]

30

Podemos además reasignar un valor a un elemento específico del array:

In [ ]:
a2[2,2]=95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[2]=np.array([45,55,65])
a2

array([[10, 20, 30],
       [40, 50, 60],
       [45, 55, 65]])

---

Si tuvieramos un array 1D, de los elementos del 1 al 20, podriamos usar indexing para seleccionar solo aquellos elementos que cumplan con una condición específica?

In [ ]:
a = np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a[a>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

O también especificar si son pares

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

## Ejercicio 1

Genera un array de 6x6 con números aleatorios entre 1 y 100 y haga las siguientes operaciones:

1. Selecciona la primera fila.
2. Selecciona la última fila.
3. Seleccione la primera fila que tenga un número par.
4. Redimensiona el array a 3x12 y selecciona la fila que su suma sea la mayor.
5. Del array 6x6 original, seleccione un subarray de 4x4


## 2.-Slicing en Arrays

En lugar de seleccionar un elemento mediante la indexación, el slicing selecciona una parte de la matriz especificando un rango.

Para una matriz unidimensional, el slicing especifica las posiciones del principio y el final, como se muestra a continuación

```python
Nombre_del_array[posición_inicial : posición_final]
```

In [ ]:
b1 = np.array([10,20,30,40,50])
b1[1:4]


array([20, 30, 40])

Otra forma de hacer slicing en un array unidimensional, puede realizarse sin especificar la posición inicial o final, de la siguiente manera:

In [ ]:
b1[:3]

array([10, 20, 30])

Aquí, los dos puntos `:` indican que se seleccionarán todos los elementos del array hasta el valor especificado como posición final es decir 3

Como sería para los arrays multidimensionales?

In [ ]:
arr2d = np.arange(1,26).reshape(5,5)
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr2d[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Cuando hacemos slicing usando [:2] estamos seleccionando las dos primeras filas de la matriz.

Pero el slicing en arrays multidimensionales puede ser más complejo. Por ejemplo, si queremos seleccionar las dos primeras filas y las dos primeras columnas de la matriz, podemos hacerlo de la siguiente manera:

In [ ]:
arr2d[:2,:2]

array([[1, 2],
       [6, 7]])

O tambien podemos usar un indice entero y un slice juntos para obtener una fila y una columna específica de la matriz:

In [ ]:
arr2d[1,2:4]

array([8, 9])

Podrias explicar que ocurre en los siguientes casos?

In [ ]:
arr2d[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [ ]:
arr2d[:,:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [ ]:
arr2d[:2,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

También podemos tener arrays de strings, y hacer slicing de la misma manera que con los arrays numéricos.

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [ ]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [ ]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

Esta última celda nos muestra que cuando hacemos una operación booleana, el resultado es un array de booleanos, y podemos usarlo para hacer slicing.

In [ ]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

## 3. Fancy Indexing

Los capítulos anteriores discutieron cómo acceder y modificar porciones de arrays usando índices simples (por ejemplo, `arr[0]`), slices (por ejemplo, `arr[:5]`), y máscaras booleanas (por ejemplo, `arr[arr > 0]`).

En esta sección, veremos otro estilo de indexación de arrays, conocido como *fancy* o indexación *vectorizada*, en la cual pasamos arrays de índices en lugar de escalares simples.
Esto nos permite acceder y modificar rápidamente subconjuntos complicados de los valores de un array.

### 3.1. Explorando Fancy Indexing

La indexación fancy es conceptualmente simple: significa pasar un array de índices para acceder a múltiples elementos del array a la vez.
Por ejemplo, considera el siguiente array:


In [ ]:
np.random.seed(0) # Se define un seed para que los numeros aleatorios sean los mismos

data = np.random.randint(0,100,10)
data

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

Supongamos que queremos acceder a tres elementos diferentes. Podríamos hacerlo así:

In [ ]:
[data[3], data[7], data[4]]

[67, 21, 67]

Alternativamente, podemos pasar una sola lista o array de índices para obtener el mismo resultado:

In [ ]:
ind = [3, 7, 4]
data[ind]


array([67, 21, 67])

Al usar arrays de índices, la forma del resultado refleja la forma de los arrays de índices en lugar de la forma del array siendo indexado, es decir, el resultado de `data[ind]` tendrá la misma forma que el array ind, en lugar de la forma del array data.

In [ ]:
ind = np.array([[3, 7],
                [4, 5]])
data[ind]


array([[67, 21],
       [67,  9]])

La indexación fancy también funciona en múltiples dimensiones. Considera el siguiente array:

In [ ]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Al igual que con la indexación estándar, el primer índice se refiere a la fila y el segundo a la columna:

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])



Al indexar `X` con `X[row, col]`, estamos seleccionando los elementos de `X` en las posiciones especificadas por los pares `(row[i], col[i])`. Así que se seleccionan los elementos de `X` en las posiciones `(0, 2)`, `(1, 1)`, y `(2, 3)`:

1. `X[0, 2]` es 2
2. `X[1, 1]` es 5
3. `X[2, 3]` es 11


Es importante recordar que con la indexación fancy el valor de retorno refleja la *forma transmitida de los índices*, en lugar de la forma del array siendo indexado.

### 3.2. Combinando Indexación

Para operaciones aún más poderosas, la indexación fancy se puede combinar con otros esquemas de indexación que hemos visto. Por ejemplo, dado el array `X`:


In [ ]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Podemos combinar índices fancy y simples:

In [ ]:
X[2, [2, 0, 1]]

También podemos combinar la indexación fancy con slicing:

In [ ]:
X[1:, [2, 0, 1]]

Y podemos combinar la indexación fancy con enmascaramiento:

In [ ]:
mask = np.array([True, False, True, False])
X[row[:, np.newaxis], mask]

Todas estas opciones de indexación combinadas llevan a un conjunto muy flexible de operaciones para acceder y modificar valores de arrays de manera eficiente.

### 3.3. Modificar Valores con Indexación Fancy

Así como la indexación fancy se puede usar para acceder a partes de un array, también se puede usar para modificar partes de un array.

Por ejemplo, imagina que tenemos un array de índices y queremos establecer los elementos correspondientes en un array a algún valor:

In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]



Podemos usar cualquier operador de asignación para esto. Por ejemplo:

In [ ]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


Es importante notar que los índices repetidos con estas operaciones pueden causar resultados potencialmente inesperados. Considera lo siguiente:

In [ ]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


¿Dónde fue el 4? Esta operación primero asigna `x[0] = 4`, seguido por `x[0] = 6`.
El resultado, por supuesto, es que `x[0]` contiene el valor 6.

Ahora considera esta operación:

In [ ]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

Podrías esperar que `x[3]` contenga el valor 2 y `x[4]` contenga el valor 3, ya que es el número de veces que se repite cada índice. ¿Por qué no es así?
Conceptualmente, esto se debe a que `x[i] += 1` se entiende como una abreviatura de `x[i] = x[i] + 1`.

 `x[i] + 1` se evalúa y luego el resultado se asigna a los índices en `x`.

Entonces, si deseas el comportamiento donde la operación se repite, puedes usar el método `at` y hacer lo siguiente:



In [ ]:
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


El método `at` realiza una aplicación in situ del operador dado en los índices especificados


### 3.4. Ejemplo: Selección de Puntos Aleatorios

Un uso común de la indexación fancy es la selección de subconjuntos de filas de una matriz.
Por ejemplo, podríamos tener una matriz de $N \times D$ que representa $N$ puntos en $D$ dimensiones, como los siguientes puntos extraídos de una distribución normal bidimensional:


In [ ]:
np.random.seed(42)

mean = [0, 0]
cov = [[1, 2],
       [2, 5]]

X = np.random.multivariate_normal(mean, cov, 100)
X.shape

(100, 2)

In [ ]:
X

array([[-4.05992582e-01, -1.12980900e+00],
       [-1.18122448e+00, -1.20321251e+00],
       [ 3.05929845e-01,  4.85151964e-01],
       [-1.75268695e+00, -3.40069525e+00],
       [ 2.26109036e-01,  1.13313826e+00],
       [ 6.06369182e-01,  9.59802450e-01],
       [ 5.08636661e-01, -8.42962089e-01],
       [ 1.80879440e+00,  3.75820034e+00],
       [ 8.15476694e-01,  2.30887376e+00],
       [ 1.37937009e+00,  1.80142746e+00],
       [-1.26768205e+00, -3.30483370e+00],
       [ 4.82839600e-01, -3.76458413e-01],
       [ 4.60495820e-01,  1.23179700e+00],
       [ 9.19606001e-01,  2.62677788e+00],
       [ 6.66544157e-01,  1.29345291e+00],
       [-1.52931750e-01,  1.63568156e+00],
       [ 4.17238258e-01, -1.37555797e-01],
       [-2.92735771e-01, -2.02815831e+00],
       [ 5.56968489e-01, -7.76490778e-01],
       [ 1.15174837e+00,  2.99364761e+00],
       [-7.47833961e-01, -1.61994320e+00],
       [ 2.22072477e-01,  2.10218094e-01],
       [ 1.64144866e+00,  3.18365385e+00],
       [ 2.

Usando la indexación fancy, podemos seleccionar 20 puntos aleatorios. Primero, elegimos 20 índices aleatorios sin repetición y usamos estos índices para seleccionar una porción del array original:

In [ ]:
indices = np.random.choice(X.shape[0], 20, replace=False)
indices

array([93, 28, 55, 30, 80, 17, 54, 76, 10,  9,  2, 87, 46, 98, 84, 82, 26,
       69, 85, 52])

In [ ]:
selection = X[indices]  # indexación fancy aquí
selection

array([[-0.40934414, -1.06707361],
       [ 0.89366635,  1.82281235],
       [ 1.78285987,  4.27550608],
       [ 0.51374789,  1.03934128],
       [ 0.59928421,  2.2987343 ],
       [-0.29273577, -2.02815831],
       [-0.20945632, -0.58625196],
       [ 0.53938128,  1.55357119],
       [-1.26768205, -3.3048337 ],
       [ 1.37937009,  1.80142746],
       [ 0.30592984,  0.48515196],
       [-0.57217829, -0.48602389],
       [ 0.77400336,  1.51395046],
       [ 0.75774974,  1.99576056],
       [ 0.5151514 ,  0.42784735],
       [-1.04800791, -2.08332405],
       [ 0.391316  ,  1.60679404],
       [-0.28056053, -2.00961096],
       [ 1.13400126,  1.85469452],
       [-0.005615  ,  0.42378568]])

## 5. Transposición de Arrays e Intercambio de Ejes

### 5.1.Transposición de Arrays

La transposición de arrays intercambia filas y columnas en un array. Considera el siguiente array:

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Transponemos el array

In [ ]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### 5.2. Intercambio de Ejes

Podemos intercambiar ejes usando `swapaxes`. Primero, creamos un array de 3x4:

Creamos y redimensionamos un array de 12 elementos:

In [ ]:
arr_1 = np.arange(12).reshape(3, 4)
arr_1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr_1.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Transponemos el array usando diferentes ejes:

In [ ]:
arr_1.transpose((0, 1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr_1.transpose((1, 0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Creamos un array de 16 elementos y lo redimensionamos a 2x2x4:

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((1, 0, 2))


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((0, 1, 2))


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((2, 1, 0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

Intercambiamos ejes del array usando `swapaxes`:

In [ ]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [ ]:
arr.swapaxes(0, 1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])